doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            point: Core\Type\Point

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        mapping_types:
            point: point
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/src/Entity'
                prefix: 'Core\Entity'
                alias: Core
